name: Build plugin

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout our code 
      - name: Checkout code
        uses: actions/checkout@v6

      # Setup NodeJS environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

      # Fetch the vendor folder from the cache, keyed off the composer.lock file 
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # install NPM dependencies
      - name: Install NPM dependencies
        run: npm install

      # build the app
      - name: Build
        run: |
          npm run build
